### ISSUE TITLE
wasm failed

### ISSUE THREAD

**Issue by cyanyiyi** [zemlyansky/arima#8]
On running server in my Vue2 application using yarn serve locally :
Uncaught RuntimeError: abort(sync fetching of the wasm failed: you can preload it to Module['wasmBinary'] manually, or emcc.py will do that for you when generating HTML (but not JS)). Build with -s ASSERTIONS=1 for more info.

**Comment by toddscottik** [comment]
I also faced with this problem. This happened because this package don't adapted to run in browser. I solved this problem when i had assemble this using browserify. There may be required to add change a third number in index.js to 
`const m = await Module({ wasmBinary: bin })`
and delete ` Module["then"]`
So this helped to me to run this package, but I also encountered some problems with working with this package.
Thanks to some guys in tg chat that help me with this.

**Comment by jornncc** [comment]
I get the same problem - can't run react app with this installed.

![image](https://user-images.githubusercontent.com/15808559/127427219-965bb7d0-65aa-4b06-81df-d2074e1fbd86.png)

**Comment by CKPOON0619** [comment]
The loading problem comes from the script `Module(bin.data)` which should be just `Module(bin)` as mentioned above. 
After that, you will need to run the script within a Webworker thread as the code is too large to instantiate. 

This repo points to an example in [statsim](https://statsim.com/forecast/) which is written by the same author showing how to use his `Port` package to run the script. 

Inside the worker.js, you can just `require('arima')` and use it no problem. 


In case if you are using webpack 5, see this [example](https://webpack.js.org/guides/web-workers/).
If you have problem parsing `import.meta`, this [plugin](https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader) may help.

However if you are using earlier version(i.e. webpack 4), you can use [worker-loader](https://github.com/webpack-contrib/worker-loader) as suggested by the guide above.

Hope this helps anyone who see to do some ARIMA :) with this brilliant library.

**Comment by zemlyansky** [comment]
Hey, sorry for reacting late.  @CKPOON0619, you are right, there's an error in the `index.js` and `Module` should load `bin`, not `bin.data`. I used to bundle a wasm file in `native.bin.js` as `module.exports = {"type":"Buffer","data":[0,97...`, but then switched to more compact representation `module.exports = toUint8Array('AGFz...`. The tricky part is, when loading `index.js` from Node, `wasmBinary` parameter is `undefined`, as in the browser, but Node doesn't throw the error, because it falls back to the original `wasm` file. So tests passed and I missed this error. 

01aef475bfab4cd3734adce0dc29217b01d275ae: changed `bin.data` to `bin` and added a browser example

**Comment by zemlyansky** [comment]
Hah, It seems that GitHub automatically closes issues based on a commit text. I'm reopening it as:

> a Webworker thread as the code is too large to instantiate. (moved to #10)

> webpack

**Comment by zemlyansky** [comment]
Added `async` mode: https://github.com/zemlyansky/arima/issues/10#issuecomment-979134187 (works in Chrome)
